language: go

go:
  - 1.7
  - tip

services:
  - postgressql

env: 
    - TBBR_DB_NAME=tbbr_test
    - TBBR_DB_USER=postgres
    - TBBR_DB_PASSWORD=

before_install:
    - curl https://glide.sh/get | sh
    - go get github.com/mattes/migrate

install: glide install

before_script:
    - psql -c 'create database tbbr_test;' -U postgres
    - migrate -url postgres://postgres@localhost:5432/tbbr_test?sslmode=disable -path ./migrations up
